apiVersion: v1
kind: Service
metadata:
  name: con1-service
spec:
  type: LoadBalancer
  ports:
    - port: 6000
      targetPort: 6000
  selector:
    app: con1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: akshit-pv-dir
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  gcePersistentDisk:
    pdName: akshit-disk
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akshit-pvc-dir
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
