apiVersion: apps/v1
kind: Deployment
metadata:
  name: con1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: con1
  template:
    metadata:
      labels:
        app: con1
    spec:
      containers:
        - name: con1
          image: us-central1-docker.pkg.dev/a3kubernetes-390219/con1-repo/con1-image:1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: data-volume
              mountPath: /app/filedata
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: akshit-pvc-dir



